all:
	g++ ./../../reference_implementations/c/beanie.h ./../../reference_implementations/c/beanie.c boomerang_probability.c -Wall -O3 -o beanie_boomerang_probability
clean:
	rm -f *.o beanie_boomerang_probability
